### ISSUE TITLE
python missing?

### ISSUE THREAD

**Issue by peterromfeldhk** [GoogleCloudPlatform/elixir-runtime#17]
```
Step #1: gyp verb check python checking for Python executable "python2" in the PATH
Step #1: gyp verb `which` failed Error: not found: python2
...
Step #1: gyp verb check python checking for Python executable "python" in the PATH
Step #1: gyp verb `which` failed Error: not found: python
```

**Comment by peterromfeldhk** [comment]
```
runtime_config:
  release_app: example
  packages:
    - python
```

did it, but you already ship nodejs for build env, so i would assume that it also has python for gyp
