### ISSUE TITLE
Cloud SQL connection problem

### ISSUE THREAD

**Issue by bruce** [GoogleCloudPlatform/elixir-runtime#18]
I'm seeing the dreaded socket connection error in my application, deploying to the flex environment.

```
Postgrex.Protocol (#PID<0.1788.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (/cloudsql/<project>:us-east1:stagingdb/.s.PGSQL.5432): no such file or directory - :enoent
... many more like it
```

I'm using postgrex v0.13.5, and the content of my `app.yaml` looks like:

```yaml
env: flex
runtime: gs://elixir-runtime/elixir.yaml
runtime_config:
  release_app: <app-name>
env_variables:
  # ... other vars                   
  POSTGRES_SOCKET_DIR: "/cloudsql/<project>:us-east1:stagingdb"
```

I'm using Postgrex' `:socket_dir` option, which they recommend. I've also tried it with the `:socket` option set to the full path, `/cloudsql/<project>:us-east1:stagingdb/.s.PGSQL.5432`, to no avail.

I've enabled all the Cloud SQL APIs I could find for my project, and my `<project>@appspot.gserviceaccount.com` account is configured with both `Editor` and `Cloud SQL Admin` roles in IAM.

If anyone has any ideas, I'd be very helpful. (I'd really like to just hop into the instance and see exactly what is/isn't in `/cloudsql`, but I can't figure out how to do that.)
