### ISSUE TITLE
Preferred method of including runtime binaries that are not available in aptitude

### ISSUE THREAD

**Issue by zgohr** [GoogleCloudPlatform/elixir-runtime#21]
According to [this discussion](https://elixirforum.com/t/is-there-a-way-to-package-binary-dependencies-with-distillery/5849) which I agree with the premise of, there is no way to have Distillery include 3rd party binaries in a release.

That leaves me needing to modify the runtime to include wkhtmltopdf with my project, and the latest available package for [Ubuntu 16 is 0.12.2.4](https://packages.ubuntu.com/search?suite=xenial&searchon=names&keywords=wkhtmltopdf) and I require the latest, 0.12.5.

Although I'm not sure exactly how, it seems I should be able to create a custom `Dockerfile` from this runtime stack and use it as a custom runtime. It would be fantastic to understand how to accomplish this, but I haven't tried this route yet.

The hack I have in place for now is to do it with a nasty entrypoint. This is undesired for a multitude of reasons.

```yaml
runtime_config:
  packages:
    - wget
    - xfonts-75dpi
    - xfonts-base

entrypoint: wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.trusty_amd64.deb && dpkg -i wkhtmltox_0.12.5-1.trusty_amd64.deb && /app/bin/myapp foreground
```

Is there currently a better way to accomplish this that wouldn't require creating a custom runtime?
