### ISSUE TITLE
Invalid runtime name

### ISSUE THREAD

**Issue by AzimLord** [GoogleCloudPlatform/elixir-runtime#31]
Hi. Im trying to deploy using standard enviroment to use the free tier for App Engine

Below are my `app.yaml`
```
env: standard
runtime: gs://elixir-runtime/elixir.yaml
runtime_config:
    release_app: my_app

beta_settings:
    cloud_sql_instances: [CONNECTION-NAME]
```

Below are the error
```
Beginning deployment of service [default]...
ERROR: (gcloud.app.deploy) Invalid runtime name: [gs://elixir-runtime/elixir.yaml]. Must match regular expression [[a-z][a-z0-9\-]{0,29}].
```

But when using `env: flex` and `env: flexible` working fine
Any help would be great. Thanks
