### ISSUE TITLE
Support for custom MIX_ENV?

### ISSUE THREAD

**Issue by stephanos** [GoogleCloudPlatform/elixir-runtime#7]
👋 I'd like to use `staging` for my staging deployments since they use different settings, but it seems `MIX_ENV` is fixed to `prod`. Is there any way to change that?

**Comment by dazuma** [comment]
App engine lets you set environment variables in the `app.yaml` file; you can set `MIX_ENV` there. That would look something like:

```yaml
env: flex
runtime: gs://elixir-runtime/elixir.yaml
# ...other settings...
env_variables:
  MIX_ENV: staging
```

Looking over the code, however, I realize that when building an _OTP release_, the env is hard-coded to `prod`. So the above will work if you're deploying without creating a distillery release, but if you're deploying a `release_app`, it's currently stuck on `prod`. I'll look into fixing that in the next day or so.
